FROM node:16.17-alpine

WORKDIR /var/www/html/excuses-de-dev/client

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

RUN chown -R node /var/www/html/excuses-de-dev/client/node_modules

USER node

EXPOSE 8000

CMD [ "npm", "run", "dev" ]