# docker-compose for dev environment
version: '3.9'

services:
  client:
    image: vue-app-dev
    stdin_open: true
    ports: 
      - "8000:8000"
    networks:
      - mevn-app
    volumes:
      - ./client:/var/www/html/excuses-de-dev/client
      - /var/www/html/excuses-de-dev/client/node_modules
  server:
    image: api-server-dev
    ports:
      - "3000:3000"
    networks:
      - mevn-app
    depends_on:
      - mongo
    volumes:
      - ./server:/var/www/html/excuses-de-dev/server
      - /var/www/html/excuses-de-dev/server/node_modules

  mongo:
    image: mongo:6.0.1-focal
    ports:
      - "27017:27017"
    networks:
      - mevn-app
    volumes:
      - ./mongo-data:/mongo-data
networks:
  mevn-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local