FROM node:16.17-alpine

WORKDIR /var/www/html/excuses-de-dev/server

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

RUN chown -R node /var/www/html/excuses-de-dev/server/node_modules

USER node

EXPOSE 3000

CMD [ "npm", "run", "start" ]